---
title: "Linking to a specific time point in the YouTube video"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Dorota Wójcik"
date: "8/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Purpose

Learn how to generate a link that can take you to a specific time point in the YouTube video.

## Prerequisites

* **Comments** option needs to be enabled for a video that you want to link to.
* Video to be linked to cannot be a live stream.

## Generate a link to a time point

To find out how to link to a specific time point in your video, you can either check the [video instruction](#video-instruction) or follow the [step-by-step guideline](#step-by-step).

### Video instruction

Learn it the quickest way: Checking [this video](https://user-images.githubusercontent.com/63733226/129481087-cc275074-d9fa-4978-8a8b-69cf973898e7.mp4) will take 20 seconds only.

### Step-by-step

1. Go to your browser and navigate to a [YouTube](https://www.youtube.com/) video that you need a time-point link for.
   
   ***NOTE***
   
   Signing in to your YouTube account is optional.

3. From the YouTube page that opens, select **SHARE** under the video area, to the right.

4. In the **Share** pop-up window, select the **Start at** checkbox, enter the time that you want to link to, and select **COPY** next to the link to be shared.

   ***RESULT***
   
   After selecting **COPY**, the link gets updated so that it leads to the time you specified for the **Start at** checkbox.
   
## Check how it works

1. Open a new tab in you browser.

2. Paste the copied link.

3. Hit **ENTER** (**return**).

4. Check if the video opens at a time that you tried to link to.

***RESULT***

You get a link that leads to a specific time point in the YouTube video. With the link, you're able to launch your video starting at a specific time.

***NOTE***

An alternative way to generate a time-point link to the YouTube video is using the **Copy video URL at current time** option, which is available after pausing your video at a desired time and right-clicking withing the video area so that the context menu shows up.